// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var Belt_Array = require("bs-platform/lib/js/belt_Array.js");

var arr = /* array */[
  "airpods",
  "not bad"
];

Belt_Array.forEach(arr, (function (s) {
        console.log(s);
        return /* () */0;
      }));

var x = 1;

var y = 2;

exports.x = x;
exports.y = y;
exports.arr = arr;
/*  Not a pure module */
