// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var Belt_Array = require("bs-platform/lib/js/belt_Array.js");

console.log("hello world");

var arr = /* array */[
  "airpods",
  "not bad"
];

Belt_Array.forEach(arr, (function (s) {
        console.log(s);
        return /* () */0;
      }));

var foo = "expressions";

var bar = "seem to be";

console.log("template expressionsseem to bepopular");

exports.arr = arr;
exports.foo = foo;
exports.bar = bar;
/*  Not a pure module */
